# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  GLFW3_config = debug
  Engine_config = debug
  Sandbox_config = debug

else ifeq ($(config),release)
  GLFW3_config = release
  Engine_config = release
  Sandbox_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := GLFW3 Engine Sandbox

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

GLFW3:
ifneq (,$(GLFW3_config))
	@echo "==== Building GLFW3 ($(GLFW3_config)) ===="
	@${MAKE} --no-print-directory -C Engine/Vendor/glfw -f Makefile config=$(GLFW3_config)
endif

Engine: GLFW3
ifneq (,$(Engine_config))
	@echo "==== Building Engine ($(Engine_config)) ===="
	@${MAKE} --no-print-directory -C Engine -f Makefile config=$(Engine_config)
endif

Sandbox: GLFW3 Engine
ifneq (,$(Sandbox_config))
	@echo "==== Building Sandbox ($(Sandbox_config)) ===="
	@${MAKE} --no-print-directory -C Sandbox -f Makefile config=$(Sandbox_config)
endif

clean:
	@${MAKE} --no-print-directory -C Engine/Vendor/glfw -f Makefile clean
	@${MAKE} --no-print-directory -C Engine -f Makefile clean
	@${MAKE} --no-print-directory -C Sandbox -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   GLFW3"
	@echo "   Engine"
	@echo "   Sandbox"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"